### ISSUE TITLE
First example failing

### ISSUE THREAD

**Issue by annapamma** [PNNL-CompBio/decomprolute#203]
Hi @sgosline 

I tried to run the first example in the docs 

```
cwltool https://raw.githubusercontent.com/PNNL-CompBio/decomprolute/main/metrics/prot-deconv.cwl --cancer hnscc --protAlg mcpcounter --sampleType tumor --signature LM7c
```

and got this error

```
Traceback (most recent call last):        
  File "/bin/protDataSetsCLI.py", line 71, in <module>
    main()
  File "/bin/protDataSetsCLI.py", line 30, in main
    dat = cptac.Hnscc()
  File "/usr/local/lib/python3.9/site-packages/cptac/hnscc.py", line 56, in __init__
    super().__init__(cancer_type="hnscc", version=version, valid_versions=valid_versions, data_files=data_files, no_internet=no_internet)
  File "/usr/local/lib/python3.9/site-packages/cptac/dataset.py", line 83, in __init__
    update_index(self._cancer_type)
  File "/usr/local/lib/python3.9/site-packages/cptac/file_download.py", line 183, in update_index
    download_file(index_url, index_path, server_index_hash, file_message=f"{dataset} index")
  File "/usr/local/lib/python3.9/site-packages/cptac/file_download.py", line 274, in download_file
    with open(path, 'wb') as dest:
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.9/site-packages/cptac/data_hnscc/index.txt'
INFO [job download-prot] Max memory used: 1369MiB
WARNING [job download-prot] exited with status: 1
ERROR Expecting value: line 1 column 1 (char 0)
script was:
01 "use strict";
02 var inputs = {
03     "cancerType": "hnscc",
04     "sampleType": "tumor"
05 };
06 var self = [];
07 var runtime = {
08     "cores": 1,
09     "ram": 1024,
10     "tmpdirSize": 1024,
11     "outdirSize": 1024,
12     "tmpdir": "/tmp",
13     "outdir": "/zCsNMH"
14 };
15 (function(){
16   var name = inputs.cancerType + '-' + inputs.sampleType + '-' + 'prot-raw.tsv'
17   self[0].basename = name;
18   return self[0]
19   })()
stdout was: ''
stderr was: 'evalmachine.<anonymous>:17
  self[0].basename = name;
                   ^

TypeError: Cannot set properties of undefined (setting 'basename')
    at evalmachine.<anonymous>:17:20
    at evalmachine.<anonymous>:19:5
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at Socket.<anonymous> ([eval]:11:57)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)'

Traceback (most recent call last):
  File "/Users/anna/venv/lib/python3.8/site-packages/cwltool/sandboxjs.py", line 384, in execjs
    return cast(CWLOutputType, json.loads(stdout))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/anna/venv/lib/python3.8/site-packages/cwltool/expression.py", line 393, in do_eval
    return interpolate(
  File "/Users/anna/venv/lib/python3.8/site-packages/cwltool/expression.py", line 297, in interpolate
    e = evaluator(
  File "/Users/anna/venv/lib/python3.8/site-packages/cwltool/expression.py", line 232, in evaluator
    return execjs(
  File "/Users/anna/venv/lib/python3.8/site-packages/cwltool/sandboxjs.py", line 386, in execjs
    raise JavascriptException(
cwltool.sandboxjs.JavascriptException: Expecting value: line 1 column 1 (char 0)
script was:
01 "use strict";
02 var inputs = {
03     "cancerType": "hnscc",
04     "sampleType": "tumor"
05 };
06 var self = [];
07 var runtime = {
08     "cores": 1,
09     "ram": 1024,
10     "tmpdirSize": 1024,
11     "outdirSize": 1024,
12     "tmpdir": "/tmp",
13     "outdir": "/zCsNMH"
14 };
15 (function(){
16   var name = inputs.cancerType + '-' + inputs.sampleType + '-' + 'prot-raw.tsv'
17   self[0].basename = name;
18   return self[0]
19   })()
stdout was: ''
stderr was: 'evalmachine.<anonymous>:17
  self[0].basename = name;
                   ^

TypeError: Cannot set properties of undefined (setting 'basename')
    at evalmachine.<anonymous>:17:20
    at evalmachine.<anonymous>:19:5
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at Socket.<anonymous> ([eval]:11:57)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)'
```

**Comment by annapamma** [comment]
Conclusion:
- works on Google Cloud linux VM (e2 instance)
- Does not work on Apple M1 machines

To do:
- Add caveat to documentation

**Comment by sgosline** [comment]
I'm working on the M1 issue now - i need to build docker containers better.

**Comment by sgosline** [comment]
should now work on M1 machines!
